
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('MBBE','Maybank');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('CIBB','CIMB BANK');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('CITI','CITIBANK');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('PBBE','PUBLIC BANK BERHAD');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('RHBB','RHB BANK BERHAD');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('HLBB','HONG LEONG BANK BERHAD');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('ARBK','AMBANK');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('BKRM','BANK RAKYAT');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('UOVB','UNITED OVERSEAS BANK');
INSERT INTO BANK (BANK_ID,BANK_NAME) VALUES ('BSNA','BANK SIMPANAN NASIONAL BERHAD');

INSERT INTO EMPLOYEE_POSITION (POSITION_ID, POSITION_NAME,POSITION_BASIC_SALARY) VALUES ('P001', 'CEO',12000);
INSERT INTO EMPLOYEE_POSITION (POSITION_ID, POSITION_NAME,POSITION_BASIC_SALARY) VALUES ('P002', 'Manager',5000);
INSERT INTO EMPLOYEE_POSITION (POSITION_ID, POSITION_NAME,POSITION_BASIC_SALARY) VALUES ('P003', 'Software Engineer',5000);
INSERT INTO EMPLOYEE_POSITION (POSITION_ID, POSITION_NAME,POSITION_BASIC_SALARY) VALUES ('P004', 'Technical Specialist',4000);
INSERT INTO EMPLOYEE_POSITION (POSITION_ID, POSITION_NAME,POSITION_BASIC_SALARY) VALUES ('P005', 'Application Developer',4000);

INSERT INTO EMPLOYEE_STATUS (STATUS_ID,STATUS_NAME) VALUES ('S01','ACTIVE');
INSERT INTO EMPLOYEE_STATUS (STATUS_ID,STATUS_NAME) VALUES ('S02','LONG LEAVE');
INSERT INTO EMPLOYEE_STATUS (STATUS_ID,STATUS_NAME) VALUES ('S03','RETIRE');
INSERT INTO EMPLOYEE_STATUS (STATUS_ID,STATUS_NAME) VALUES ('S04','LEFT COMPANY');
INSERT INTO EMPLOYEE_STATUS (STATUS_ID,STATUS_NAME) VALUES ('S05','MEDICAL LEAVE');

INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D00','ADMINISTRATION');
INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D01','R&D');
INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D02','TESTING');
INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D03','FINANCE');
INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D04','TECHNICAL SUPPORT');
INSERT INTO DEPARTMENT (department_id,DEPARTMENT_NAME) VALUES ('D05','HR');
