SELECT * FROM PAYSLIP;

--TEST TRG ADD ROW PAYSLIP_ALLOWANCE TRIGGER TTL_ALLOWANCE
INSERT INTO PAYSLIP_ALLOWANCE (PAYSLIP_NUM, ALLOWANCE_ID) VALUES ('AA03_1119', 'AL_PET');
--TEST TRG CHANGE ALLOWANCE_AMOUNT
UPDATE ALLOWANCE SET ALLOWANCE_AMOUNT=600 WHERE ALLOWANCE_ID='AL_PET';

--TEST tRG ADD ROW PAYSLIP_INCENTIVE TRIGGER TTL_INCENTIVE
INSERT INTO PAYSLIP_INCENTIVE (PAYSLIP_NUM, INCENTIVE_ID, INCENTIVE_AMOUNT) VALUES ('AA03_1119', 'IN_EMP', 500);
--TEST TRG CHANGE INCENTIVE_AMOUNT TRIGGER TTL_INCENTIVE
UPDATE PAYSLIP_INCENTIVE SET INCENTIVE_AMOUNT=900 WHERE PAYSLIP_NUM='AA03_1119' AND INCENTIVE_ID='IN_PRO';

--TEST TRG ADD ROW PAYSLIP_DEDUCTION TRIGGER TTL_DEDUCTION
INSERT INTO PAYSLIP_DEDUCTION (PAYSLIP_NUM, DEDUCTION_ID) VALUES ('AA03_1119', 'SOCSO');
--TEST TRG CHANGE ALLOWANCE_AMOUNT
UPDATE DEDUCTION SET DEDUCTION_RATE=50 WHERE DEDUCTION_ID='EIS';



SELECT SALARY FROM EMPLOYEE LEFT JOIN EMPLOYEE_POSITION USING (POSITION_ID) WHERE EMPLOYEE_ID IN(
SELECT EMPLOYEE_ID FROM PAYSLIP WHERE PAYSLIP_NUM IN(
SELECT PAYSLIP_NUM FROM PAYSLIP_ALLOWANCE LEFT JOIN PAYSLIP USING (PAYSLIP_NUM) GROUP BY PAYSLIP_NUM)
)
;

ROLLBACK;
