--SUM OF ALLOWANCE OF ALL PAYSLIP

SELECT PAYSLIP_ALLOWANCE.PAYSLIP_NUM, SUM(ALLOWANCE_AMOUNT) FROM PAYSLIP_ALLOWANCE LEFT JOIN ALLOWANCE ON PAYSLIP_ALLOWANCE.ALLOWANCE_ID=ALLOWANCE.ALLOWANCE_ID
GROUP BY PAYSLIP_ALLOWANCE.PAYSLIP_NUM;

--TEST TGR ADD ROW PAYSLIP_ALLOWANCE TRIGGER TTL_ALLOWANCE

INSERT INTO PAYSLIP_ALLOWANCE (PAYSLIP_NUM, ALLOWANCE_ID) VALUES ('AA02_1119', 'AL_PET');

--TEST TGR CHANGE ALLOWANCE_AMOUNT
UPDATE ALLOWANCE SET ALLOWANCE_AMOUNT=600 WHERE ALLOWANCE_ID='AL_PET';

SELECT * FROM PAYSLIP;
ROLLBACK;
