--TRG ADD ROW PAYSLIP_ALLOWANCE TRIGGER TTL_ALLOWANCE

CREATE OR REPLACE TRIGGER TRG_PAYSLIP_ALLOWANCE
AFTER INSERT OR UPDATE ON PAYSLIP_ALLOWANCE
FOR EACH ROW
BEGIN
    UPDATE PAYSLIP SET TOTAL_ALLOWANCE=(
    SELECT SUM(ALLOWANCE_AMOUNT) FROM PAYSLIP_ALLOWANCE LEFT JOIN ALLOWANCE ON PAYSLIP_ALLOWANCE.ALLOWANCE_ID=ALLOWANCE.ALLOWANCE_ID
    WHERE PAYSLIP.PAYSLIP_NUM=PAYSLIP_ALLOWANCE.PAYSLIP_NUM 
    GROUP BY PAYSLIP_ALLOWANCE.PAYSLIP_NUM 
    );

END;

--TRG CHANGE ALLOWANCE_AMOUNT

--CREATE OR REPLACE TRIGGER TRG_ALLOWANCE
--AFTER INSERT OR UPDATE ON ALLOWANCE
--BEGIN
--UPDATE PAYSLIP SET TOTAL_ALLOWANCE=(
--SELECT SUM(ALLOWANCE_AMOUNT) FROM PAYSLIP_ALLOWANCE LEFT JOIN ALLOWANCE ON PAYSLIP_ALLOWANCE.ALLOWANCE_ID=ALLOWANCE.ALLOWANCE_ID
--WHERE PAYSLIP.PAYSLIP_NUM=PAYSLIP_ALLOWANCE.PAYSLIP_NUM GROUP BY PAYSLIP_ALLOWANCE.PAYSLIP_NUM 
--);
--END;



